// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgqp96LgYnH6_YmAQchktVxP8_YLJf41c',
    appId: '1:202482506460:web:57325e504791c3c336f219',
    messagingSenderId: '202482506460',
    projectId: 'playspace-1db5b',
    authDomain: 'playspace-1db5b.firebaseapp.com',
    databaseURL: 'https://playspace-1db5b-default-rtdb.firebaseio.com',
    storageBucket: 'playspace-1db5b.firebasestorage.app',
    measurementId: 'G-4XT0ET1YVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjnFtRIyUgk0vJv4ECEqe_Js70epwdK1E',
    appId: '1:202482506460:android:9e986a19677e830836f219',
    messagingSenderId: '202482506460',
    projectId: 'playspace-1db5b',
    databaseURL: 'https://playspace-1db5b-default-rtdb.firebaseio.com',
    storageBucket: 'playspace-1db5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA0FpZJx6fil7NHc-rDqtGtJHTSxT20UQ',
    appId: '1:202482506460:ios:84506cecfbdc6c6f36f219',
    messagingSenderId: '202482506460',
    projectId: 'playspace-1db5b',
    databaseURL: 'https://playspace-1db5b-default-rtdb.firebaseio.com',
    storageBucket: 'playspace-1db5b.firebasestorage.app',
    iosBundleId: 'com.example.playspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA0FpZJx6fil7NHc-rDqtGtJHTSxT20UQ',
    appId: '1:202482506460:ios:84506cecfbdc6c6f36f219',
    messagingSenderId: '202482506460',
    projectId: 'playspace-1db5b',
    databaseURL: 'https://playspace-1db5b-default-rtdb.firebaseio.com',
    storageBucket: 'playspace-1db5b.firebasestorage.app',
    iosBundleId: 'com.example.playspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgqp96LgYnH6_YmAQchktVxP8_YLJf41c',
    appId: '1:202482506460:web:dd6445660c2f756536f219',
    messagingSenderId: '202482506460',
    projectId: 'playspace-1db5b',
    authDomain: 'playspace-1db5b.firebaseapp.com',
    databaseURL: 'https://playspace-1db5b-default-rtdb.firebaseio.com',
    storageBucket: 'playspace-1db5b.firebasestorage.app',
    measurementId: 'G-2T041B3J5Q',
  );
}
